---
image_definition: &image_definition
  platform: linux

  image_resource:
    type: docker-image
    source:
      repository: openjdk
      tag: 8-jdk

resource_types:
- name: twitter
  type: docker-image
  source:
    repository: ecsteam/twitter-concourse-resource

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/kirederik/spring-petclinic.git
    branch: concourse-live-demo
- name: cloudfoundry
  type: cf #from https://github.com/concourse/cf-resource
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true
- name: tweet # https://github.com/ECSTeam/twitter-resource
  type: twitter
  source:
    consumer_key: {{twitter-consumer-key}}
    consumer_secret: {{twitter-consumer-secret}}
    access_token: {{twitter-access-token}}
    access_token_secret: {{twitter-access-token-secret}}

jobs:
- name: build
  plan:
  - get: source-code
    trigger: true
  - task: build
    config:
      <<: *image_definition

      inputs:
      - name: source-code
        path: .

      run:
        path: ./mvnw
        args:
          - compile

- name: test
  plan:
  - get: source-code
    trigger: true
    passed: [build]
  - task: test
    config:
      <<: *image_definition
      inputs:
      - name: source-code
        path: .

      run:
        path: ./mvnw
        args:
          - test

- name: deploy
  plan:
  - get: source-code
    trigger: true
    passed: [test]
  - task: package
    config:
      <<: *image_definition
      inputs:
      - name: source-code
      outputs:
      - name: package
      run:
        path: /bin/bash
        args:
          - -c
          - |
            set -eu
            pushd source-code
            ./mvnw package
            cp target/spring-petclinic*.jar ../package/app.jar
            popd
  - put: cloudfoundry
    params:
      manifest: source-code/manifest.yml
      path: package/app.jar
      current_app_name: springpetclinic # for blue green deployment
    on_success:
      put: tweet
      params:
        status: >
          A new version of the PetClinic is available (build ${BUILD_ID})! Check it out!
