---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/dlresende/spring-petclinic.git
    branch: concourse-live-demo
- name: cloudfoundry
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: build
  plan:
  - get: source-code
    trigger: true
  - task: build
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8-jdk

      inputs:
      - name: source-code
        path: .

      run:
        path: ./mvnw
        args:
          - compile

- name: test
  plan:
  - get: source-code
    trigger: true
    passed: [build]
  - task: test
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8-jdk

      inputs:
      - name: source-code
        path: .

      run:
        path: ./mvnw
        args:
          - test

- name: deploy
  plan:
  - get: source-code
    trigger: true
    passed: [test]
  - put: cloudfoundry
    params:
      manifest: source-code/manifest.yml
      path: source-code
